import { ResumeViewer } from '@/components/resume/ResumeViewer';
import { heroEmail } from '@/config/Hero';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Resume',
  description:
    'Mehfooj Alam, AI Engineer. One page resume covering agent runtimes, backend systems and the work behind them.',
  alternates: { canonical: '/resume' },
};

/**
 * The resume, rendered from a PDF that CI rebuilds from LaTeX.
 *
 * The PDF in `public/resume` is generated by `.github/workflows/resume.yml` from
 * `src/data/resume/main.tex`. That indirection is the whole point: the LaTeX
 * source is the single source of truth, the workflow recompiles it whenever it
 * changes, and this page never holds a second copy that could drift.
 *
 * Compiling at build time instead would need a LaTeX toolchain in the Vercel
 * image, which would add hundreds of megabytes to every deploy of every route.
 */
export default function ResumePage() {
  return (
    <div className="mx-auto w-full max-w-3xl px-4 pt-6 pb-16 sm:pt-9 sm:pb-20">
      <h1 className="text-foreground text-2xl font-bold tracking-tight sm:text-3xl">
        Resume
      </h1>
      <p className="text-muted-foreground mt-3 max-w-xl text-[15px] leading-7">
        One page, covering the agent runtimes and backend systems behind them.
        Generated from LaTeX on every change to the source, so it never goes out
        of date.
      </p>

      <div className="mt-8">
        <ResumeViewer
          src="/resume/mehfooj-alam-resume.pdf"
          title="Mehfooj Alam resume"
        />
      </div>

      {/* Provenance. Worth stating plainly: what this file is, where it comes
          from, and what happens when it changes. */}
      <dl className="border-border/70 divide-border/70 mt-8 divide-y border-y text-sm">
        <div className="grid gap-1 py-3 sm:grid-cols-[7rem_1fr] sm:gap-4">
          <dt className="text-muted-foreground font-mono text-xs tracking-[0.14em] uppercase">
            source
          </dt>
          <dd className="text-foreground">
            <code className="font-mono text-[13px]">
              src/data/resume/main.tex
            </code>
          </dd>
        </div>
        <div className="grid gap-1 py-3 sm:grid-cols-[7rem_1fr] sm:gap-4">
          <dt className="text-muted-foreground font-mono text-xs tracking-[0.14em] uppercase">
            pipeline
          </dt>
          <dd className="text-foreground">
            Push to the source, CI recompiles the PDF, this page serves the new
            build.
          </dd>
        </div>
        <div className="grid gap-1 py-3 sm:grid-cols-[7rem_1fr] sm:gap-4">
          <dt className="text-muted-foreground font-mono text-xs tracking-[0.14em] uppercase">
            elsewhere
          </dt>
          <dd className="text-foreground">
            A role tailored version lives at{' '}
            <a
              href="https://github.com/tsvlgd/ResumeVersions"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent hover:underline"
            >
              ResumeVersions
            </a>
            , which holds the full stack and backend variants built from the
            same source.
          </dd>
        </div>
      </dl>

      <p className="text-muted-foreground mt-8 text-[15px] leading-7">
        The fastest way to reach me is{' '}
        <a href={`mailto:${heroEmail}`} className="text-accent hover:underline">
          email
        </a>
        . A longer account of the work lives on the{' '}
        <Link href="/work-experience" className="text-accent hover:underline">
          work page
        </Link>
        .
      </p>
    </div>
  );
}
